### ISSUE TITLE
Feature Request: OCI Preemption Event Handling and Node Replacement

### ISSUE THREAD

**Issue by Macbet** [zoom/karpenter-oci#11]
Problem Statement:

Karpenter for OCI (karpenter-oci) lacks proactive handling of OCI Preemptible Instance terminations. Currently, there's no pre-notification when a Preemptible Instance is marked for termination, leading to abrupt workload disruptions and delayed node replacement. This contrasts with karpenter-aws, which uses SQS for timely EC2 Spot interruption warnings, enabling graceful node replacement and pod draining.

Proposed Solution
Implement OCI Events integration in karpenter-oci to subscribe to Preemptible Instance termination events. Upon receiving an event, Karpenter should:

Identify the affected node.

Immediately provision a new node.

(Highly desirable) Gracefully cordon and drain pods from the old node to the new one before termination.

**Comment by wy0824** [comment]
Hello @Macbet , we will add this feature to the roadmap, and there is a related PR: https://github.com/zoom/karpenter-oci/pull/6

**Comment by Macbet** [comment]
Hello! I hope I can get some time in my company to send PR with support for this functionality

**Comment by dannyeuu** [comment]
Today, preemptible nodes work? with:
```yaml
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - preemptible
            - spot
```

But no `preemptible` is created, only `on-demand`
