### ISSUE TITLE
[FLEX INSTANCES] Problem on OCPU vs vCPU consolidation

### ISSUE THREAD

**Issue by dannyeuu** [zoom/karpenter-oci#19]
Karpenter-OCI Controller version: 1.4.0-alpha01 and 1.0.9-build05

Found a problem for Flex Intances:
```
{"level":"DEBUG","time":"2025-06-20T15:10:40.989Z","logger":"controller","caller":"disruption/controller.go:99","message":"marking consolidatable","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-kqdtz"},"namespace":"","name":"karpenter-arm64-pool-kqdtz","reconcileID":"adf30837-55a0-47e4-9546-393fa1f931d8","Node":{"name":"10.137.193.57"}}
{"level":"DEBUG","time":"2025-06-20T15:10:47.975Z","logger":"controller","caller":"disruption/controller.go:99","message":"marking consolidatable","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-2pbbl"},"namespace":"","name":"karpenter-arm64-pool-2pbbl","reconcileID":"7aa40044-2e56-4fdb-a349-c2bbe71bf9b3","Node":{"name":"10.137.199.61"}}
{"level":"DEBUG","time":"2025-06-20T15:11:00.756Z","logger":"controller","caller":"disruption/controller.go:99","message":"marking consolidatable","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-9qxqk"},"namespace":"","name":"karpenter-arm64-pool-9qxqk","reconcileID":"16e49114-3890-425b-b008-d9caea5e57c4","Node":{"name":"10.137.203.31"}}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-2pbbl"},"namespace":"","name":"karpenter-arm64-pool-2pbbl","reconcileID":"c02f5386-471c-412c-a86b-e9cc9791dbdd","Node":{"name":"10.137.199.61"},"error":"expected 96 of resource cpu, but found 48 (50.0% of expected)"}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-k84jf"},"namespace":"","name":"karpenter-arm64-pool-k84jf","reconcileID":"7d16a439-ccb7-4e51-bc6e-f20a4e1e4ee2","Node":{"name":"10.137.193.161"},"error":"expected 64 of resource cpu, but found 32 (50.0% of expected)"}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-kqdtz"},"namespace":"","name":"karpenter-arm64-pool-kqdtz","reconcileID":"0483a96a-2645-4bce-bca5-a879b71a0857","Node":{"name":"10.137.193.57"},"error":"expected 96 of resource cpu, but found 48 (50.0% of expected)"}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-9qxqk"},"namespace":"","name":"karpenter-arm64-pool-9qxqk","reconcileID":"00efe0f5-8323-42c2-8ec0-738466ef045e","Node":{"name":"10.137.203.31"},"error":"expected 64 of resource cpu, but found 32 (50.0% of expected)"}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-wzqxq"},"namespace":"","name":"karpenter-arm64-pool-wzqxq","reconcileID":"8523887e-cd50-406f-93ad-cbd5f0f723c3","Node":{"name":"10.137.194.173"},"error":"expected 96 of resource cpu, but found 48 (50.0% of expected)"}
{"level":"ERROR","time":"2025-06-20T15:16:56.136Z","logger":"controller","caller":"consistency/controller.go:110","message":"consistency error","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"karpenter-arm64-pool-rjlkk"},"namespace":"","name":"karpenter-arm64-pool-rjlkk","reconcileID":"1e8c06ba-f0dc-4607-8e60-3fe9cf84e696","Node":{"name":"10.137.203.216"},"error":"expected 32 of resource cpu, but found 16 (50.0% of expected)"}

```

The `NodeClaim` are getting vCPU on Capacity and in `Node` are getting the Capacity / 2.0

`Node`:
```yaml
status:                                                                                                                                                                                                                                       
  addresses:                                                                                                                                                                                                                                  
  - address: 10.137.193.57                                                                                                                                                                                                                    
    type: InternalIP                                                                                                                                                                                                                          
  - address: 10.137.193.57                                                                                                                                                                                                                    
    type: Hostname                                                                                                                                                                                                                            
  allocatable:                                                                                                                                                                                                                                
    cpu: 47900m                                                                                                                                                                                                                               
    ephemeral-storage: "85814201407"                                                                                                                                                                                                          
    hugepages-1Gi: "0"                                                                                                                                                                                                                        
    hugepages-2Mi: "0"                                                                                                                                                                                                                        
    hugepages-32Mi: "0"                                                                                                                                                                                                                       
    hugepages-64Ki: "0"                                                                                                                                                                                                                       
    memory: 394115660Ki                                                                                                                                                                                                                       
    pods: "110"                                                                                                                                                                                                                               
  capacity:                                                                                                                                                                                                                                   
    cpu: "48"                                                                                                                                                                                                                                 
    ephemeral-storage: 90932Mi                                                                                                                                                                                                                
    hugepages-1Gi: "0"                                                                                                                                                                                                                        
    hugepages-2Mi: "0"                                                                                                                                                                                                                        
    hugepages-32Mi: "0"                                                                                                                                                                                                                       
    hugepages-64Ki: "0"                                                                                                                                                                                                                       
    memory: 394986060Ki                                                                                                                                                                                                                       
    pods: "110"   
```

`NodeClaim`:
```yaml
status:                                                                                                                                                                                                                                       
  allocatable:                                                                                                                                                                                                                                
    cpu: 95583m                                                                                                                                                                                                                               
    ephemeral-storage: 89Gi                                                                                                                                                                                                                   
    memory: 348416Mi                                                                                                                                                                                                                          
    pods: "110"                                                                                                                                                                                                                               
  capacity:                                                                                                                                                                                                                                   
    cpu: "96"                                                                                                                                                                                                                                 
    ephemeral-storage: 100Gi                                                                                                                                                                                                                  
    memory: 363724Mi                                                                                                                                                                                                                          
    pods: "110"  
```

on Nodes deployed by OKE the Node `status.capacity.cpu` are equals to vCPU and not the OCPU
