### ISSUE TITLE
[FLEXIBLE INSTANCES] Invalid Preemptible instance shape: VM.Standard.A2.Flex (is not supported)

### ISSUE THREAD

**Issue by dannyeuu** [zoom/karpenter-oci#24]
Karpenter "freezes" and not replace nodes after a NodeClaim got this error:
```
INFO 2025/06/29 20:26:18.234813 log.go:229: Dump Request Body: 
{"agentConfig":{"pluginsConfig":[{"desiredState":"ENABLED","name":"Bastion"}]},"availabilityDomain":"BZgz:US-ASHBURN-AD-1","compartmentId":"ocid1.compartment.oc1..aaaaaaaa","createVnicDetails":{"nsgIds":["ocid1.networksecuritygroup.oc1.iad.aaaaaaaa"[],"subnetId":"ocid1.subnet.oc1.iad.aaaaaaaa"},"definedTags":{"oke-karpenter-ns":{"karpenter_k8s_oracle/ocinodeclass":"karpenter-arm64-class","karpenter_sh/managed-by":"databases","karpenter_sh/nodepool":"karpenter-arm64-pool"}},"displayName":"karpenter-arm64-pool-m445d","instanceOptions":{"areLegacyImdsEndpointsDisabled":true},"launchVolumeAttachments":[],"metadata":{"ssh_authorized_keys":"ssh-rsa AAAAA== Notebook","user_data":"AAAA===="},"preemptibleInstanceConfig":{"preemptionAction":{"preserveBootVolume":false,"type":"TERMINATE"}},"shape":"VM.Standard.A2.Flex","shapeConfig":{"memoryInGBs":488,"ocpus":61},"sourceDetails":{"bootVolumeSizeInGBs":100,"bootVolumeVpusPerGB":10,"imageId":"ocid1.image.oc1.iad.aaaaaaaa","sourceType":"image"}}
INFO 2025/06/29 20:26:18.234932 client.go:465: Dump Response HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 125
Content-Type: application/json
Date: Sun, 29 Jun 2025 20:26:17 GMT
Opc-Request-Id: 3bfbad2a7167e7d350f7762805984342/61DD29AF69C271EDD36BAFB2173FB41C/7A15F06D2887B01A8897B1F7BB957E55
Strict-Transport-Security: max-age=31536000; includeSubDomains;
X-Content-Type-Options: nosniff

{
  "code" : "InvalidParameter",
  "message" : "Invalid Preemptible instance shape: VM.Standard.A2.Flex (is not supported)"
}
```

LunchInstance Body:
```yaml
{
    "agentConfig":
    {
        "pluginsConfig":
        [
            {
                "desiredState": "ENABLED",
                "name": "Bastion"
            }
        ]
    },
    "availabilityDomain": "BZgz:US-ASHBURN-AD-1",
    "compartmentId": "ocid1.compartment.oc1..aaaaaaaa",
    "createVnicDetails":
    {
        "nsgIds":
        [
            "ocid1.networksecuritygroup.oc1.iad.aaaaaaaa"
        ],
        "subnetId": "ocid1.subnet.oc1.iad.aaaaaaaa"
    },
    "definedTags":
    {
        "oke-karpenter-ns":
        {
            "karpenter_k8s_oracle/ocinodeclass": "karpenter-arm64-class",
            "karpenter_sh/managed-by": "databases",
            "karpenter_sh/nodepool": "karpenter-arm64-pool"
        }
    },
    "displayName": "karpenter-arm64-pool-2x2gg",
    "instanceOptions":
    {
        "areLegacyImdsEndpointsDisabled": true
    },
    "launchVolumeAttachments":
    [],
    "metadata":
    {
        "ssh_authorized_keys": "ssh-rsa AAAAA== Notebook",
        "user_data": "AAAA===="
    },
    "preemptibleInstanceConfig":
    {
        "preemptionAction":
        {
            "preserveBootVolume": false,
            "type": "TERMINATE"
        }
    },
    "shape": "VM.Standard.A2.Flex",
    "shapeConfig":
    {
        "memoryInGBs": 480,
        "ocpus": 60
    },
    "sourceDetails":
    {
        "bootVolumeSizeInGBs": 100,
        "bootVolumeVpusPerGB": 10,
        "imageId": "ocid1.image.oc1.iad.aaaaaaaa",
        "sourceType": "image"
    }
}
```
