### ISSUE TITLE
[NODE REGISTRATION] New nodes are create the NodeClaim, creates the instance but not getting registrated

### ISSUE THREAD

**Issue by dannyeuu** [zoom/karpenter-oci#8]
Firstly, I would like to congratulate the Zoom team on this project and commend them for keeping it open source. thanks.

I am testing and creating an OKE PoC to use https://github.com/kubernetes-sigs/karpenter in OCI, but I got an issue, the nodes are created, but are not registered.

The configs that I am using are:

```yaml
---
apiVersion: karpenter.k8s.oracle/v1alpha1
kind: OciNodeClass
metadata:
  name: karpenter-ubuntu-arm64-class
  namespace: karpenter
spec:
  imageSelector:
    - name: Canonical-Ubuntu-22.04-aarch64-2025.03.28-0
      compartmentId: ocid1.compartment.oc1..AAAAAAAAAAAAAAAAAAA
  imageFamily: Ubuntu2204

  # ───────── Boot Volume Configuration ─────────
  bootConfig:
    bootVolumeSizeInGBs: 100
    bootVolumeVpusPerGB: 10

  # ───────── Kubelet Tuning (Optional) ─────────
  kubelet:
    systemReserved:
      cpu: "100m"
      memory: "100Mi"
    evictionHard:
      memory.available: "750Mi" 
      nodefs.available: "10%"
      nodefs.inodesFree: "5%"

  # ───────── Network ‐ Subnet & VCN ‐─────────
  vcnId: ocid1.vcn.oc1.iad.AAAAAAAAAAAAAAAAAAAAAAAAAAAA
  subnetSelector:
    - name: large-private-subnet-vcn-default-data      # Match by the “name:” field of your existing OCI Subnet.
  # (If you need multiple subnets, add more entries in the list.)

  # ───────── Metadata for Native CNI (if using) ─────────
  # If your OKE cluster is using the OKE “native” CNI instead of an overlay, uncomment:
  # metaData:
  #   oke-native-pod-networking: "true"

  # ───────── Tags (Optional) ─────────
  # You can also define freeformTags or definedTags here to propagate to each node.
  # tags:
  #   karpenter_k8s_oracle/ocinodeclass: karpenter-amd64-class
  #   karpenter_sh/managed-by: databases-oci-data-infopriceti-com-br
  #   karpenter_sh/nodepool: karpenter-amd64-pool
  securityGroupSelector:
    - name: karpenter-nsg
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-ubuntu-arm64-pool
  namespace: karpenter
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m

  limits:
    cpu: 64
    memory: 300Gi

  template:
    metadata:
      labels:
        servicegroup: karpenter-ubuntu-arm64-class

    spec:
      expireAfter: Never

      nodeClassRef:
        group: karpenter.k8s.oracle
        kind: OciNodeClass
        name: karpenter-ubuntu-arm64-class

      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        
        # - key: karpenter.k8s.oracle/is-flexible
        #   operator: In
        #   values:
        #     - "true"

        # # - key: karpenter.k8s.oracle/instance-shape-name
        # #   operator: In
        # #   values:
        # #     - VM.Standard.A1.Flex
        # #     - VM.Standard.A2.Flex

        # - key: karpenter.k8s.oracle/instance-cpu
        #   operator: In
        #   values:
        #     - "2"
        #     - "4"
        #     - "8"
        #     - "16"
        #     - "32"

        # - key: karpenter.k8s.oracle/instance-memory
        #   operator: In
        #   values:
        #     - "1024" # 1GB
        #     - "2048" # 2GB
        #     - "4096" # 4GB
        #     - "8192" # 8GB
        #     - "16384" # 16GB
        #     - "32768" # 32GB
        #     - "65536" # 64GB
        #     - "131072" # 128GB

        # This gets added automatically because the image is aarch64:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64 

        - key: kubernetes.io/os
          operator: In
          values:
            - linux

      terminationGracePeriod: 30m

```

```yaml
apiVersion: karpenter.k8s.oracle/v1alpha1
kind: OciNodeClass
metadata:
  name: karpenter-arm64-class
  namespace: karpenter
spec:
  imageSelector:
    - name: Oracle-Linux-8.10-aarch64-2025.02.28-0-OKE-1.32.1-760
      compartmentId: ocid1.compartment.oc1..AAAAAAAAAAAAAAAAAA
  imageFamily: OracleOKELinux

  # ───────── Boot Volume Configuration ─────────
  bootConfig:
    bootVolumeSizeInGBs: 100
    bootVolumeVpusPerGB: 10

  # ───────── Kubelet Tuning (Optional) ─────────
  kubelet:
    systemReserved:
      cpu: "100m"
      memory: "100Mi"
    evictionHard:
      memory.available: "750Mi" 
      nodefs.available: "10%"
      nodefs.inodesFree: "5%"

  # ───────── Network ‐ Subnet & VCN ‐─────────
  vcnId: ocid1.vcn.oc1.iad.AAAAAAAAAAAAAAAAAAAA
  subnetSelector:
    - name: large-private-subnet-vcn-default-data      # Match by the “name:” field of your existing OCI Subnet.
  # (If you need multiple subnets, add more entries in the list.)

  # ───────── Metadata for Native CNI (if using) ─────────
  # If your OKE cluster is using the OKE “native” CNI instead of an overlay, uncomment:
  # metaData:
  #   oke-native-pod-networking: "true"

  # ───────── Tags (Optional) ─────────
  # You can also define freeformTags or definedTags here to propagate to each node.
  # tags:
  #   karpenter_k8s_oracle/ocinodeclass: karpenter-amd64-class
  #   karpenter_sh/managed-by: databases-oci-data-infopriceti-com-br
  #   karpenter_sh/nodepool: karpenter-amd64-pool
  securityGroupSelector:
    - name: karpenter-nsg
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: karpenter-arm64-pool
  namespace: karpenter
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m

  limits:
    cpu: 64
    memory: 300Gi

  template:
    metadata:
      labels:
        servicegroup: karpenter-arm64-class

    spec:
      expireAfter: Never

      nodeClassRef:
        group: karpenter.k8s.oracle
        kind: OciNodeClass
        name: karpenter-arm64-class

      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        
        # - key: karpenter.k8s.oracle/is-flexible
        #   operator: In
        #   values:
        #     - "true"

        # # - key: karpenter.k8s.oracle/instance-shape-name
        # #   operator: In
        # #   values:
        # #     - VM.Standard.A1.Flex
        # #     - VM.Standard.A2.Flex

        # - key: karpenter.k8s.oracle/instance-cpu
        #   operator: In
        #   values:
        #     - "2"
        #     - "4"
        #     - "8"
        #     - "16"
        #     - "32"

        # - key: karpenter.k8s.oracle/instance-memory
        #   operator: In
        #   values:
        #     - "1024" # 1GB
        #     - "2048" # 2GB
        #     - "4096" # 4GB
        #     - "8192" # 8GB
        #     - "16384" # 16GB
        #     - "32768" # 32GB
        #     - "65536" # 64GB
        #     - "131072" # 128GB

        # This gets added automatically because the image is aarch64:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64

        - key: kubernetes.io/os
          operator: In
          values:
            - linux

      terminationGracePeriod: 30m

```

![Image](https://github.com/user-attachments/assets/ed22953d-e2ec-4bb8-8219-265eea4374a4)

![Image](https://github.com/user-attachments/assets/f4d1b9f0-5770-4641-9760-58472f689a2c)

PS: We at https://github.com/InfoPrice do not have Go software engineers, but if you have something that we can do, just ask.
